# Generated by Django 5.1.6 on 2025-02-28 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Заголовок')),
                ('short_content', models.TextField(blank=True, verbose_name='Краткое содержание')),
                ('content', models.TextField(blank=True, verbose_name='Полное содержание')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2025, 2, 28, 8, 35, 14, 469061), verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-posted'],
            },
        ),
    ]
