# Generated by Django 5.1.6 on 2025-03-02 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2025, 3, 2, 22, 38, 59, 306232), verbose_name='Опубликована'),
        ),
    ]
